### ISSUE TITLE
www subdomain not properly configured

### ISSUE THREAD

**Issue by aoleson** [computinged-uw/computinged-uw.github.io#1]
The site lives at https://computinged.uw.edu, but https://www.computinged.uw.edu does not properly redirect there and fails with an IP lookup error (ERR_NAME_NOT_RESOLVED).
Tested on Firefox 73.0.1 (64-bit) and Chrome 80.0.3987.132 (64-bit). 

Since it looks like the CNAME record in this repo is set up correctly, this error is probably due to an incorrectly configured CNAME record on the DNS provider's (in this case, UW's) side. See e.g. step #4 under "Configuring a Subdomain" here: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

Step 3 "Create DNS entries" of this StackOverflow question should do the trick: https://stackoverflow.com/questions/9082499/custom-domain-for-github-project-pages

As an example, here's the records I added on my DNS provider's admin panel to fix the problem on my personal site which lives at `aoleson.github.io`: 
![Screen Shot 2020-03-04 at 10 52 29 AM](https://user-images.githubusercontent.com/9409198/75912767-945a9300-5e06-11ea-92cb-a04e0dd4657e.png)

**Comment by amyjko** [comment]
Is there a reason that `www.computinged.uw.edu` should resolve? Some UW sites do (e.g., `https://www.ischool.uw.edu` redirects), but `https://www.dub.washington.edu` does not.

**Comment by aoleson** [comment]
No particular functionality reason I suppose, I see it more as a usability issue. Most sites today redirect by default, so end users may not know the difference between `www.computinged.uw.edu` and `computinged.uw.edu` If a person tries to navigate to `www.computinged.uw.edu` and gets an error, they may not know how to proceed and might just give up on finding the site.

**Comment by amyjko** [comment]
Archiving repo.
